# Generated by Django 5.1 on 2024-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('major_crop', models.CharField(max_length=100)),
                ('area_of_farm', models.FloatField()),
                ('selling_period', models.DateField()),
                ('quantity_of_crop', models.FloatField()),
                ('price_expectations', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
