# Generated by Django 5.1 on 2024-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('crop_name', models.CharField(max_length=100)),
                ('quantity_needs', models.FloatField()),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_till', models.DateField()),
            ],
        ),
    ]
